services:
  camunda:
    image: 'camunda/camunda-bpm-platform:wildfly-7.21.0'
    volumes:
      - ./storage:/storage
    environment:
      - 'PHOTO_STORAGE=/storage'
      - 'MESSAGES_LOG=/messages_info.log'
    ports:
      - "8080:8080"
      - "9990:9990"
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db1'
      - 'POSTGRES_PASSWORD=11gramgim'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
  postgres2:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db2'
      - 'POSTGRES_PASSWORD=11gramgim'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5433:5432"
  localRabbitMQ:
    hostname: localRabbitMQ
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"
  lab4micro:
    build: ./RatingService
    restart: always
    volumes:
      - ./RatingService:/app
    ports:
      - "8188:8188"
#  lab4:
#    build: .
#    restart: always
#    volumes:
#      - .:/app
#    ports:
#      - "8177:8177"
#
